language: java
dist: trusty
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
install: true
script:
    - "./gradlew clean"
    - "./gradlew exhaustiveTest"
    - "if [[ -n $TRAVIS_TAG ]]; then
          ./gradlew ship;
      else
          ./gradlew build;
      fi"
cache:
  gradle: true
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
branches:
  only:
  - master
  - /^\d+\.\d+\.(\d|[x])+(-SNAPSHOT|-alpha|-beta)?\d*$/ # trigger builds on tags which are semantically versioned to ship the SDK.

# Integration tests need to run first to reset the PR build status to pending
stages:
  - 'Integration tests'
  - 'Test'

jobs:
  include:
    - stage: 'Integration tests'
      env: SDK=java
      cache: false
      language: minimal
      install:
        - mkdir $HOME/travisci-tools && pushd $HOME/travisci-tools && git init && git pull https://$CI_USER_TOKEN@github.com/optimizely/travisci-tools.git && popd
      script:
        - "$HOME/travisci-tools/fsc-trigger/trigger_fullstack-sdk-compat.sh"
